# Linear albegra for AI
There are many vectors definitions but here we will focus on $\mathbb{R}^n$ (tuple of n real number), this is an example:
$$
\textbf{a} = \begin{bmatrix}1\cr2\cr3\cr4\end{bmatrix} \in \mathbb{R}^4
$$

This means that the vector $\textbf{a}$ composed by four real number belongs to $\mathbb{R}^4$.

## Liner Equation
Linear equation came from real world problem:
> A company has to produce $N_1 ... N_n$ products, each product needs the resources $R_1 ... R_m$.
>
> Each resources is limited to $b_j$ so $R_1 ... R_m$ resources are limited to $b_1 ... b_m$ units.
>
> Find the optimized number of products $x_1 ... x_n$ which can be produced having maximum $b_1 ... b_m$ resources.
>
> Use $a_{ij}$ as the number of resource $R_j$ used by the product $N_i$.

This problem can be approched finding the number of the same resource $b_1$ used by the $N_1 ... N_n$  products:

$$
x_1 a_{11} + x_2 a_{21} + ... + x_n a_{n1}  = b_1\ (Number\ of\ available\ R_1\ resources)\\
x_1 a_{12} + x_2 a_{22} + ... + x_n a_{n2}  = b_2\\
...\\
x_1 a_{1m} + x_2 a_{2m} + ... + x_n a_{nm}  = b_m
$$

We can group the $x_1 ... x_n$ and write the above equations as:

$$
\begin{bmatrix}a_{11}  \cr a_{12}  \cr ...  \cr a_{1m} \end{bmatrix} x_1 + \begin{bmatrix}a_{21}  \cr a_{22}  \cr ...  \cr a_{2m} \end{bmatrix} x_2 + ... + \begin{bmatrix}a_{n1}  \cr a_{n2}  \cr ...  \cr a_{nm} \end{bmatrix} x_n = \begin{bmatrix}b_1  \cr b_2  \cr ...  \cr b_m \end{bmatrix}
$$

Grouping also the $a_{ij}$ in a matrix and the $x_i$ in a vector we have:

$$
\begin{bmatrix}a_{11} & a_{21} & ... & a_{n1}\cr a_{12} & a_{22} & ... & a_{n2}\cr ... & ... & ... & ...\cr a_{1m} & a_{2m} & ... & a_{nm}\end{bmatrix} \begin{bmatrix}x_1\cr x_2\cr ...\cr x_n\end{bmatrix} = \begin{bmatrix}b_1\cr b_2\cr ...\cr b_m\end{bmatrix}
$$


### Matrices property
In the above equation we have used the matrix notation, here we will see some properties of matrices.

#### General properties
1. $\textbf{A} \in \mathbb{R}^{row\ num\ \times\ col\ num}$ is the general form of a matrix, the exponent define the dimension so $A \in \mathbb{R}^{m \times n}$ is composed by $m$ rows and $n$ columns.
2. $\textbf{A} \in \mathbb{R}^{m \times n}$ can be equivalently written as $\textbf{a} \in \mathbb{R}^{mn}$, this is called the vectorization of the matrix and it is done by stacking the columns of the matrix.

#### Operations

##### Sum is commutative
$\textbf{A} + \textbf{B} = \textbf{B} + \textbf{A}$, the sum of two matrices is commutative. 


In [1]:
import numpy as np

mat1 = np.array([[1, 2], [3, 1]])
mat2 = np.array([[3, 0], [-1, 2]])
print(f"Matrix 1:\n{mat1}")
print(f"Matrix 2:\n{mat2}")
print(f"Matrix 1 + Matrix 2:\n{mat1 + mat2}")

Matrix 1:
[[1 2]
 [3 1]]
Matrix 2:
[[ 3  0]
 [-1  2]]
Matrix 1 + Matrix 2:
[[4 2]
 [2 3]]


The same result is obtained by changing the order of the matrices.

In [2]:
print(f"Matrix 2 + Matrix 1:\n{mat2 + mat1}")

Matrix 2 + Matrix 1:
[[4 2]
 [2 3]]


2. $A \cdot \textbf{B} \neq \textbf{B} \cdot \textbf{A}$, the product of two matrices is not commutative, indeed:

In [3]:
print(mat1 @ mat2)

[[1 4]
 [8 2]]


In [14]:
print(mat2 @ mat1)

[[3 6]
 [5 0]]

##### Product dimension
The product of a matrix $\textbf{A} \in \mathbb{R}^{m \times n}$ with another matrix $\textbf{B} \in \mathbb{R}^{n \times p}$ is a matrix $\textbf{C} \in \mathbb{R}^{m \times p}$. As you can see the result matrix has the number of rows of the first matrix and the number of columns of the second matrix.

$$\underbrace{\textbf{A}}_{\textbf{m} \times n} \cdot \underbrace{\textbf{B}}_{n \times \textbf{p}} = \underbrace{\textbf{C}}_{\textbf{m} \times \textbf{p}}$$

Only "neighboring" matrices can be multiplied, so $\textbf{A} \in \mathbb{R}^{m \times n}$ can be multiplied by $\textbf{B} \in \mathbb{R}^{n \times p}$ but not by $\textbf{C} \in \mathbb{R}^{p \times q}$.

##### Element-wise multiplication
Matrix multiplication is not a element-wise multiplication, so $c_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj}$ but not $c_{ij} = a_{ij} b_{ij}$.

#### Mixed properties:

##### Associative property
$(A \cdot B) \cdot C = A \cdot (B \cdot C)\ \ \ \  \forall A \in \mathbb{R}^{m \times n}, B \in \mathbb{R}^{n \times p}, C \in \mathbb{R}^{p \times q}$

##### Distributive property
$A \cdot (B + C) = A \cdot B + A \cdot C\quad\forall A \in \mathbb{R}^{m \times n}, B \in \mathbb{R}^{n \times p}, C \in \mathbb{R}^{n \times p}$

#### Identity matrix:
1. The identity matrix $\textbf{I}$ is a square matrix with ones in the diagonal and zeros elsewhere.
2. The identity matrix is the neutral element of the matrix multiplication, so $\textbf{A} \cdot \textbf{I} = \textbf{A}$.
3. The identity matrix is the neutral element of the matrix sum, so $\textbf{A} + \textbf{I} = \textbf{A}$.

#### Inverse matrix:
The inverse of a matrix $\textbf{A}$ is denoted as $\textbf{A}^{-1}$ and it is defined as the matrix that multiplied by $\textbf{A}$ gives the identity matrix $\textbf{I}$.

The adjugate matrix of a matrix is the matrix obtained by replacing each element with its